// examples/vue-vite/src/FormView.vue
<script setup lang="ts">
import {
  FormFlow,
  FormFlowField,
  FormFlowHoneypot,
  isChoiceField,
  type FormSchema,
} from '@formflowjs/vue';

// Headless rendering: every element below is OUR markup with utility
// (Tailwind-ish) class names. `@formflowjs/vue` ships no CSS — it only computes the
// `v-bind` prop bags (value, handlers, accessibility, `data-*` state).
defineProps<{ schema: FormSchema; baseUrl: string }>();
</script>

<template>
  <FormFlow
    :form="schema"
    :options="{ baseUrl, validateOn: 'blur' }"
    v-slot="form"
  >
    <p v-if="form.status.value === 'success'" class="ff-alert ff-alert--success">
      {{ form.result.value?.message ?? 'Thank you for your submission!' }}
    </p>

    <form v-else v-bind="form.formProps.value" class="ff-form">
      <FormFlowField
        v-for="f in form.fields.value"
        :key="f.name"
        :name="f.name"
        v-slot="field"
      >
        <!-- Display-only heading fields have no input. -->
        <h2 v-if="f.type === 'heading'" class="ff-form__heading">{{ f.label }}</h2>

        <div v-else class="ff-field" :data-invalid="field.invalid.value || undefined">
          <label v-bind="field.labelProps.value" class="ff-field__label">
            {{ f.label }}
            <span v-if="f.required" class="ff-field__req"> *</span>
          </label>

          <!-- textarea -->
          <textarea
            v-if="f.type === 'textarea'"
            v-bind="field.inputProps.value"
            class="ff-input ff-input--area"
            rows="4"
          />

          <!-- select -->
          <select
            v-else-if="f.type === 'select'"
            v-bind="field.inputProps.value"
            class="ff-input"
          >
            <option value="">Select…</option>
            <option v-for="opt in f.options" :key="opt.value" :value="opt.value">
              {{ opt.label }}
            </option>
          </select>

          <!-- checkbox / radio choice group -->
          <div
            v-else-if="isChoiceField(f.type) && f.options"
            v-bind="field.controlProps.value"
            class="ff-choices"
          >
            <label
              v-for="opt in f.options"
              :key="opt.value"
              class="ff-choice"
            >
              <input v-bind="field.getOptionProps(opt.value)" class="ff-choice__box" />
              <span>{{ opt.label }}</span>
            </label>
          </div>

          <!-- file -->
          <input
            v-else-if="f.type === 'file'"
            v-bind="field.getInputProps({ type: 'file' })"
            class="ff-input ff-input--file"
          />

          <!-- plain text-like inputs -->
          <input
            v-else
            v-bind="field.getInputProps({
              type: f.type === 'email' ? 'email' : f.type === 'number' ? 'number' : f.type === 'url' ? 'url' : 'text',
            })"
            class="ff-input"
          />

          <p v-if="f.description" v-bind="field.descriptionProps.value" class="ff-field__hint">
            {{ f.description }}
          </p>
          <p v-if="field.invalid.value" v-bind="field.errorProps.value" class="ff-field__error">
            {{ field.error.value }}
          </p>
        </div>
      </FormFlowField>

      <!-- Renders the schema-declared spam honeypot (hidden), if configured. -->
      <FormFlowHoneypot />

      <button type="submit" class="ff-form__submit" :disabled="form.isSubmitting.value">
        {{ form.isSubmitting.value ? 'Submitting…' : (schema.settings.submitButtonText || 'Submit') }}
      </button>
    </form>
  </FormFlow>
</template>

// examples/react-vite/src/FormView.tsx
import {
  FormFlowField,
  FormFlowHoneypot,
  FormFlowProvider,
  isChoiceField,
  useFormFlow,
  type FormSchema,
} from '@formflowjs/react';

/**
 * Renders one form headlessly. Every element is OUR markup with utility
 * (Tailwind-ish) class names — the SDK ships no CSS and only wires behaviour,
 * accessibility, and `data-*` state. Swap the classes for your own design
 * system and nothing else changes.
 */
export function FormView({ schema, baseUrl }: { schema: FormSchema; baseUrl: string }) {
  return (
    <FormFlowProvider
      form={schema}
      baseUrl={baseUrl}
      options={{
        validateOn: 'blur',
        onSubmitSuccess: (result) => console.log('Submitted:', result),
      }}
    >
      <FormBody />
    </FormFlowProvider>
  );
}

function FormBody() {
  const { schema, fields, getFormProps, isSubmitting, status, result } = useFormFlow();

  if (status === 'success') {
    return (
      <p className="ff-alert ff-alert--success">
        {result?.message ?? 'Thank you for your submission!'}
      </p>
    );
  }

  return (
    <form {...getFormProps()} className="ff-form">
      {fields.map((f) => (
        <FormFlowField
          key={f.name}
          name={f.name}
          render={(field) => {
            // Layout/display-only fields (e.g. `heading`) have no input.
            if (field.field.type === 'heading') {
              return <h2 className="ff-form__heading">{field.field.label}</h2>;
            }

            return (
              <div className="ff-field" data-invalid={field.invalid || undefined}>
                <label {...field.getLabelProps()} className="ff-field__label">
                  {field.field.label}
                  {field.field.required && <span className="ff-field__req"> *</span>}
                </label>

                {renderControl(field)}

                {field.field.description && (
                  <p {...field.getDescriptionProps()} className="ff-field__hint">
                    {field.field.description}
                  </p>
                )}
                {field.invalid && (
                  <p {...field.getErrorProps()} className="ff-field__error">
                    {field.error}
                  </p>
                )}
              </div>
            );
          }}
        />
      ))}

      {/* Renders the schema-declared spam honeypot (hidden), if configured. */}
      <FormFlowHoneypot />

      <button type="submit" className="ff-form__submit" disabled={isSubmitting}>
        {isSubmitting ? 'Submitting…' : schema.settings.submitButtonText || 'Submit'}
      </button>
    </form>
  );
}

/** Pick the right control per field type. Headless: classes are ours. */
function renderControl(field: Parameters<NonNullable<React.ComponentProps<typeof FormFlowField>['render']>>[0]) {
  const { type } = field.field;

  if (type === 'textarea') {
    return <textarea {...field.getTextareaProps()} className="ff-input ff-input--area" rows={4} />;
  }

  if (type === 'select') {
    return (
      <select {...field.getSelectProps()} className="ff-input">
        <option value="">Select…</option>
        {field.field.options?.map((opt) => (
          <option key={opt.value} value={opt.value}>
            {opt.label}
          </option>
        ))}
      </select>
    );
  }

  if (isChoiceField(field.field.type) && field.field.options) {
    return (
      <div {...field.getControlProps()} className="ff-choices">
        {field.field.options.map((opt) => (
          <label key={opt.value} {...field.getOptionProps(opt.value)} className="ff-choice">
            <input {...field.getCheckboxProps(opt.value)} className="ff-choice__box" />
            <span>{opt.label}</span>
          </label>
        ))}
      </div>
    );
  }

  if (type === 'file') {
    return <input {...field.getFileProps()} className="ff-input ff-input--file" />;
  }

  // Plain text-like inputs (text/email/number/url/phone/date/…).
  const inputType =
    type === 'email' ? 'email' : type === 'number' ? 'number' : type === 'url' ? 'url' : 'text';
  return <input {...field.getInputProps({ type: inputType })} className="ff-input" />;
}
